<?php
/**
 * Copyright © 2016 AddShoppers.com
 * @author Santiago Moreno <smoreno91@gmail.com>
 * */
class Addshoppers_Marketingtools_IndexController extends Mage_Core_Controller_Front_Action
{

	/**
	 * Log addshoppers exceptions/error/info
	 * @param  $message
	 * @return 
	 */
	private function _logAddshoppersMsg($message){
		$string = $message;
        if(is_array($message)){
            $string = $this->arrayToString("array", $message);
        }
	
		Mage::log("[AddShoppers] :: ".$string, null, 'addshoppers.log');
	}

    /**
	 * Convert an array to string
	 * @param  $message
	 * @return 
	 */
    public function arrayToString($parentKey, $array){
        $string = "";
        foreach ($array as $key => $value) {
            $string .= is_array($value) ? $this->arrayToString($key, $value) : "$key:$value,";
        }
        return "$parentKey:[$string]";
    }

    public function socialLoginAction(){

		// Getting Api Key from Admin Panel
		$AddShoppersSecret = Mage::helper('addshoppers/config')->getApiSecret();

		// Validate signature 
		$params 	= json_decode($_GET["data"]);
		$signature 	= null;
		$p 			= array();
		 

		foreach($params as $key => $value)
		{
    		if($key == "signature")
        		$signature = $value;
    		else
        		$p[] = $key . "=" . $value;
    		$pos = strpos($key, "_email");
    		if($pos){
        		$userEmail = $value;
        		$urlemail = $value;
    		}
		}

		asort($p);
		$query = $AddShoppersSecret . implode($p);
		$hashed = hash("md5", $query);
		if($signature !== $hashed){
			$this->_logAddshoppersMsg("Invalid AddShoppers key or bad signature request.");
			die;
		}
		    
		// Signature validated, this is a valid request... continue on
		$urluser 	= $_GET["asusrnm"];

		// Checking params
		if(!$urluser){
			//die("Invalid AddShoppers params.");
		}
		if(!$urlemail){
			//die("Invalid AddShoppers params");
		}

		//Split name into first name and last name
		$arr 		= explode('_',trim($urluser));
		$firstname 	= $arr[0];
		$lastname 	= array_shift($arr);
		$lastname 	= implode(" ", $arr);
		$email 		= $urlemail;

		//Check if user is logged in
		if(Mage::getSingleton('customer/session')->isLoggedIn()){
			die();
		}

		//Preparing data
		$customer_email = $email;  		// email adress that will pass by the questionaire 
		$customer_fname = $firstname;   // first name from api 
		$customer_lname = $lastname;    // last name from api 
		$passwordLength = 10;           // the lenght of autogenerated password

		//Getting Website ID
		$websiteId = Mage::app()->getWebsite()->getId();

		// Instantiate object (this is the most important part)
		$customer = Mage::getModel('customer/customer');
		$customer->setWebsiteId($websiteId);

		//Loading customer by email
		$customer->loadByEmail($customer_email);

		//Prepare session variable to be initialize
		$session = Mage::getSingleton('customer/session');

		//If customer exists, login customer.. otherwise create a nuew customer
		if(!$customer->getId()) {

			//Preparing data for new customers
		  	$customer->setEmail($customer_email); 
		  	$customer->setFirstname($customer_fname);
		  	$customer->setLastname($customer_lname);
		  	$pass = $customer->generatePassword($passwordLength);
		  	$customer->setPassword($pass);

		  	//Attempt to create new customer
			try{
		  		//Save the data and send the new account email.    
		  		$customer->save();
		  		$customer->setConfirmation(null);
		  		$customer->save(); 
		  		$customer->sendNewAccountEmail();
			}

			//Register error in log file
			catch(Exception $e){
		 		$this->_logAddshoppersMsg($e->getMessage());
			}

			// Login new customer
			
        	$session->login($email, $pass);
        	$session->setCustomerAsLoggedIn($customer);

		}
		else {
			//Login existence customer. Customer object is already loaded
        	$session->setCustomerAsLoggedIn($customer);// this is secure because we validated the Social Login call using the signature and secret key
		}

		//Reloding page (production)
		echo '<script type="text/javascript">
				window.onload = function refreshParent(){ 
    				window.parent.location.reload(true);
				}
			</script>';
    }

}
