<div class="advice <?php echo $this->getAdviceClass() ?>">
    <div>
        <span>
            <?php if($this->isFreeShipping()) : ?>
                <?php echo $this->__('Tu pedido aplica para un envío gratuito') ?>
            <?php else : ?>
                <?php echo $this->__('A tu pedido le falta $%s para aplicar para envío gratuito', $this->getRemainingValue()) ?>
            <?php endif; ?>
        </span>
    </div>
</div>

