<?php
/**
 * Magento
 * Impirme el botón de Pago para elegirlo en método de pago
 * https://cms-assets.tutsplus.com/uploads/users/413/posts/23539/image/create-a-custom-payment-method-in-magento-part-two-checkout-process.png
 * @author     Ejepe
 */
$bcommerce = new Bcommerce_Paymethod_Model_Bcommerce();
// Registra Compra
$bcommerce->getParams();
?>
<!-- Imprime Imagen Credibanco -->
<img src="http://52.202.212.211/bcommercelinux/logo-default.png" alt="Credibanco" width="307" height="124" style="width:307px !important; height:124px !important;" border="0">
