<div id="promobanner" style="<?php if($this->checkIfFirst()) { $this->setCookie(); echo "display:block"; } ?>">
    <div class="modal-content">
        <span class="close">&times;</span>
        <img src="<?php echo $this->getSkinUrl('images/promobanner/modal-01.png') ?>">

        <section id="newsletterform">
            <form>
                <input required type="text" name="name" id="name" placeholder="Nombre">
                <input required type="text" name="email" id="email" placeholder="Correo electrónico">
                <button name="send-news" data-handle="envio" type="submit" style="display:none">Yo quiero</button>

                <div style="margin:0 auto;text-align: center;padding-top: 20px;">
                    <input type="checkbox" name="politicas" style="display:inline-block"><span class="politicas" style="display:inline-block;padding-left: 5px">Acepto la <a href="<?php echo Mage::getBaseUrl() ?>politica-privacidad"> política de privacidad</a> de BUENOSMOTIVOS</span>
                </div>

            </form>
        </section>
    </div>
</div>


<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(".close").click(function () {
            jQuery("#promobanner").hide();
        });

        jQuery("input[name='politicas']").click(function() {
            if(jQuery(this).is(":checked")){
                jQuery("button[data-handle='envio']").show();
                jQuery(this).hide();
                jQuery('.politicas').hide();
            } else {
                jQuery("button[data-handle='envio']").hide();
            }
        });
    });
</script>