<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    GetSocial
 * @package     GetSocial_SharingButtons
 * @copyright   Copyright (c) 2015 GetSocial (http://getsocial.io/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php

$get_social_api_url = Mage::getModel('core/variable')->loadByCode('gs-url-api')->getValue('text');
$get_social_lang = Mage::getModel('core/variable')->loadByCode('gs-lang')->getValue('text');
$get_social_id = Mage::getModel('core/variable')->loadByCode('gs-identifier')->getValue('text');

// Only inject GS Library if the user already has an API KEY
if (sizeof(Mage::getModel('core/variable')->loadByCode('gs-api-key')->getData()) != 0) { ?>

<script>

var gs_url_api = <?php echo $get_social_api_url ?>;
var GETSOCIAL_ID = "<?php echo $get_social_id ?>"; 
var GETSOCIAL_LANG = "<?php echo $get_social_lang ?>"; 

(function() { 
	var po = document.createElement("script"); 
	po.type = "text/javascript"; 
	po.async = true; 
	po.src = gs_url_api + '/widget/v1/gs_async.js?id=' + GETSOCIAL_ID; 
	var s = document.getElementsByTagName("script")[0]; 
	s.parentNode.insertBefore(po, s);})();
</script>

<?php } ?>