<?php

/**
 * template to display custom social login interface
 */
if (Mage::helper('sociallogin/loginhelper')->isAlreadyLoggedIn()) {
    echo '<div class="block"><div class="block-title"><strong><span>' . __('Social Login') . '</span></strong></div>';
    $userName = Mage::getSingleton('customer/session')->getCustomer()->getName();
    if ($loginRadiusAvatar = trim($this->getAvatar(Mage::getSingleton('customer/session')->getCustomer()->getId()))
    ) {
        echo '<div class="block-content"><p class="empty"><img style="float:left" width="50" height="50" src="' . $loginRadiusAvatar . '" /><span style="clear:both; float:left">' . __("Welcome") . '!  $userName </span></p></div></div>';
    } else {
        echo '<div class="block-content" style="height:20px"><p class="empty"><span style="clear:both; float:left">' . __("Welcome") . '! '.$userName.' </span></p></div></div>';
    }
} else {
    $this->getSocialLoginContainer();
}